export const ActionTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  MODIFY_QTY: "MODIFY_QTY",
  LOAD_CURRENT_ITEM: "LOAD_CURRENT_ITEM",
  IS_IN_CART: "IS_IN_CART",
};
